import { toMarkdown } from "../shared.js";

export function createBacklogSkill() {
  return toMarkdown([
    "# Backlog Workflow",
    "",
    "Use this skill whenever the agent is asked to deliver work through the markdown backlog.",
    "",
    "## Objectives",
    "",
    "- Keep requests visible as markdown tasks instead of implicit chat state.",
    "- Make scope, acceptance, and verification inspectable in the repository.",
    "- Limit work in progress so the agent does not drift across unrelated changes.",
    "",
    "## Scenario Routing",
    "",
    "- Use `backlog-research` when the input is still an idea, project request, or loosely scoped feature.",
    "- Use `backlog-planning` when research exists and needs to be converted into executable backlog items.",
    "- Use `backlog-readiness` when a single backlog item must be reviewed before implementation starts.",
    "- Use `backlog-execution` when a ready item is being implemented.",
    "",
    "## Operating Rules",
    "",
    "- Start by reading `.agents/backlog/README.md` and the active task file.",
    "- Treat the task markdown as the execution contract for the current change.",
    "- Update the task file when scope, assumptions, or validation change.",
    "- Do not close a task before code, tests, and docs reflect the same outcome.",
    "",
    "## Task Structure",
    "",
    "Use `.agents/backlog/task-template.md` for new tasks.",
    "",
    "- `Context`: the problem and timing.",
    "- `Scope`: clear boundaries for the current change.",
    "- `Acceptance Criteria`: user-visible or system-visible outcomes.",
    "- `Implementation Notes`: constraints, dependencies, and affected files.",
    "- `Verification`: tests, manual checks, and evidence.",
    "- `Decision Log`: important tradeoffs made during execution.",
    "",
    "## State Changes",
    "",
    "- `inbox/` to `ready/`: task is clear enough to implement.",
    "- `ready/` to `in-progress/`: work has started.",
    "- `in-progress/` to `done/`: implementation and validation are complete.",
  ]);
}
