import { toMarkdown } from "../shared.js";

export function createBacklogResearchSkill() {
  return toMarkdown([
    "# Backlog Research",
    "",
    "Use this skill when the agent receives an idea for a feature or project that is not implementation-ready yet.",
    "",
    "## Goal",
    "",
    "- Turn a loose request into durable implementation context stored in the repository.",
    "- Identify the parts of the codebase, tests, and systems that are likely to be touched.",
    "- Surface risks, assumptions, and open questions before backlog planning begins.",
    "",
    "## Inputs",
    "",
    "- A feature idea, product request, bug theme, or project initiative.",
    "- Optional chat context, existing docs, or links to related code.",
    "",
    "## Workflow",
    "",
    "1. Restate the goal and identify any blocking ambiguities.",
    "2. Inspect the repository structure, relevant modules, and nearby tests.",
    "3. List the files, systems, and interfaces that are likely to change.",
    "4. Capture constraints, dependencies, migration concerns, and rollout risks.",
    "5. Propose one or more implementation directions with tradeoffs.",
    "6. Outline how the work should be verified, including affected existing tests.",
    "",
    "## Research Output",
    "",
    "Store the result as a markdown document, preferably under `.agents/backlog/research/`.",
    "",
    "- `Goal`: what needs to change and why.",
    "- `Relevant Areas`: files, modules, systems, and integration points.",
    "- `Implementation Notes`: expected change shape and technical constraints.",
    "- `Test Impact`: existing tests that likely need updates or expansion.",
    "- `Verification Plan`: automated and manual validation ideas.",
    "- `Open Questions`: decisions that require user input or product clarification.",
    "",
    "## Quality Bar",
    "",
    "- Do not stop at a high-level summary; name the concrete files and code areas when they can be identified.",
    "- Call out uncertainty explicitly instead of pretending the repository is clearer than it is.",
    "- Leave enough detail that another agent can create backlog items without rereading the entire codebase.",
  ]);
}
