import { toMarkdown } from "../shared.js";

export function createBacklogReadinessSkill() {
  return toMarkdown([
    "# Backlog Readiness",
    "",
    "Use this skill when a backlog item must be evaluated before it is handed to an implementation agent.",
    "",
    "## Goal",
    "",
    "- Decide whether the item is ready, needs refinement, or is blocked.",
    "- Identify the missing information that would cause execution drift or rework.",
    "",
    "## Review Checklist",
    "",
    "- Is the scope narrow enough to implement in one focused change?",
    "- Are the acceptance criteria observable and specific?",
    "- Are dependencies, blockers, and parent links explicit?",
    "- Does the item point to the right research or surrounding context?",
    "- Are the likely files, systems, or interfaces named?",
    "- Is there a realistic verification plan?",
    "- Are there unresolved decisions that should be answered before coding starts?",
    "",
    "## Output Format",
    "",
    "Return a short readiness review with:",
    "",
    "- `Verdict`: `ready`, `needs-work`, or `blocked`.",
    "- `What is solid`: the parts of the item that are already implementation-safe.",
    "- `Gaps`: the missing information or weak assumptions.",
    "- `Required follow-up`: the minimum changes needed before execution.",
    "",
    "## Rules",
    "",
    "- Be strict about ambiguity that would create wasted coding effort.",
    "- Do not ask for perfect detail when the missing information is non-blocking.",
    "- Prefer concrete fixes to generic feedback.",
  ]);
}
