import { toMarkdown } from "../shared.js";

export function createBacklogPlanningSkill() {
  return toMarkdown([
    "# Backlog Planning",
    "",
    "Use this skill when research exists and the next step is to create backlog items for implementation.",
    "",
    "## Goal",
    "",
    "- Convert research into a backlog that is ordered, linked, and executable by agents.",
    "- Split work into the hierarchy `project -> epic -> task -> subtask` when the scope requires it.",
    "- Remove hidden context from the plan so work can be picked up asynchronously.",
    "",
    "## Workflow",
    "",
    "1. Read the research document and extract the concrete deliverables.",
    "2. Identify unresolved questions that block planning; ask the user only when the decision changes scope or sequencing.",
    "3. Group work into projects, epics, tasks, and subtasks based on delivery boundaries.",
    "4. Assign execution order, priority, parent-child relationships, and dependencies.",
    "5. Make each backlog item specific enough for implementation, testing, and review.",
    "6. Link every backlog item back to the relevant research.",
    "",
    "## Planning Rules",
    "",
    "- Prefer small tasks with clear outcomes over large mixed-scope items.",
    "- Split discovery work from implementation work when uncertainty is still high.",
    "- Use dependencies to model sequencing instead of burying order inside prose.",
    "- Each task should describe what changes, where it likely changes, and how success will be checked.",
    "",
    "## Minimum Output",
    "",
    "Each created backlog item should include:",
    "",
    "- a stable identifier and type;",
    "- a short human-readable title;",
    "- parent links and dependency links where needed;",
    "- acceptance criteria that describe the expected result;",
    "- implementation notes with likely affected files or systems;",
    "- a verification plan that another agent can execute.",
  ]);
}
