import { toMarkdown } from "./shared.js";

export function createBacklogReadme() {
  return toMarkdown([
    "# Agent Backlog",
    "",
    "Use this backlog to turn project requests into auditable markdown tasks for the agent.",
    "",
    "## Directories",
    "",
    "- `inbox/`: raw requests and notes that still need scope refinement.",
    "- `ready/`: well-scoped tasks with acceptance criteria and known dependencies.",
    "- `in-progress/`: the single task or small batch currently being executed.",
    "- `done/`: completed tasks with verification notes and links to the delivered change.",
    "",
    "## Task Lifecycle",
    "",
    "1. Capture new requests in `inbox/` as soon as they appear.",
    "2. Rewrite the request into an execution-ready task in `ready/` using `task-template.md`.",
    "3. Move the task into `in-progress/` when work actually starts.",
    "4. Record decisions, risks, and verification in the same task file while implementing.",
    "5. Move the task into `done/` after code, tests, and documentation are in sync.",
    "",
    "## Naming",
    "",
    "Use stable file names such as `AF-001-initialize-cli.md` so backlog history stays easy to follow.",
  ]);
}

export function createTaskTemplate() {
  return toMarkdown([
    "# AF-000 Task Title",
    "",
    "## Context",
    "",
    "- Why does this work matter now?",
    "- What user or system problem does it solve?",
    "",
    "## Scope",
    "",
    "- In scope:",
    "- Out of scope:",
    "",
    "## Acceptance Criteria",
    "",
    "- [ ]",
    "- [ ]",
    "",
    "## Implementation Notes",
    "",
    "- Constraints:",
    "- Dependencies:",
    "- Relevant files or systems:",
    "",
    "## Verification",
    "",
    "- [ ] Tests updated or added",
    "- [ ] Docs updated if behavior changed",
    "- [ ] Manual validation recorded",
    "",
    "## Decision Log",
    "",
    "-",
  ]);
}
